# 4.9 IC Task 4.9 Part 1

# Table of Contents

#### Step 3 - Import libraries

#### Step 4 - Wrangle the data

#### Step 5 - Data consistency checks

#### Step 5(a) - Mixed-type data

#### Step 5(b) - Missing values

#### Step 5(c) - Duplicates

#### Step 5(d) - Other checks

#### Step 6 - Combine and export data

# Step 3 - Import libraries

In [4]:
# Import libraries

import pandas as pd
import numpy as np
import os

In [6]:
# Import new customer dataset as a dataframe

path = r'C:\Users\dirk8\CareerFoundry Projects\03-2025 Instacart Basket Analysis'
cust_raw = pd.read_csv(os.path.join(path, 'Data', 'Original Data', 'EX 4.3', 'customers.csv'), index_col = False)

# Step 4 - Wrangle the data

__Step 4: Examine imported dataset, wrangle the data__

In [8]:
# Check the dimensions
cust_raw.shape

(206209, 10)

In [14]:
# Check the profile and datatypes
cust_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 206209 entries, 0 to 206208
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   user_id       206209 non-null  int64
 1   First Name    194950 non-null  object
 2   Surnam        206209 non-null  object
 3   Gender        206209 non-null  object
 4   STATE         206209 non-null  object
 5   Age           206209 non-null  int64
 6   date_joined   206209 non-null  object
 7   n_dependants  206209 non-null  int64
 8   fam_status    206209 non-null  object
 9   income        206209 non-null  int64
dtypes: int64(4), object(6)
memory usage: 15.7+ MB

In [12]:
# Check the output
cust_raw.head()

,user_id,First Name,Surnam,Gender,STATE,Age,date_joined,n_dependants,fam_status,income
0,26711,Deborah,Esquivel,Female,Missouri,48,1/1/2017,3,married,165665
1,33890,Patricia,Hart,Female,New Mexico,36,1/1/2017,0,single,59285
2,65803,Kenneth,Farley,Male,Idaho,35,1/1/2017,2,married,99568
3,125935,Michelle,Hicks,Female,Iowa,40,1/1/2017,0,single,42049
4,130797,Ann,Gilmore,Female,Maryland,26,1/1/2017,1,married,40374

In [16]:
# Check the output last records
cust_raw.tail()

,user_id,First Name,Surnam,Gender,STATE,Age,date_joined,n_dependants,fam_status,income
206204,168073,Lisa,Case,Female,North Carolina,44,4/1/2020,1,married,148828
206205,49635,Jeremy,Robbins,Male,Hawaii,62,4/1/2020,3,married,168639
206206,135902,Doris,Richmond,Female,Missouri,66,4/1/2020,2,married,53374
206207,81095,Rose,Rollins,Female,California,27,4/1/2020,1,married,99799
206208,80148,Cynthia,Noble,Female,New York,55,4/1/2020,1,married,57095

In [18]:
# Rename columns to modify existing dataframe

cust_raw.rename(columns = {'First Name' : 'first_name', 'Surnam' : 'last_name', 'Gender' : 'gender', 'STATE' : 'state_name', 'Age' : 'age', 'n_dependants' : 'number_dependents', 'fam_status' : 'married_status'}, inplace = True)

In [20]:
# Check the output
cust_raw.head(1)

,user_id,first_name,last_name,gender,state_name,age,date_joined,number_dependents,married_status,income
0,26711,Deborah,Esquivel,Female,Missouri,48,1/1/2017,3,married,165665

__Note: I will change many columns (below) with an "object" datatype to 'str' ("string") just in case these are not stored as string datatypes.__

In [24]:
# Change some column datatypes (str e.g. string is more efficient and uses less storage than an object datatype)
# Change user_id to 'str' to match the other ords_prods_merge df datatype for this column, as it's a key identifier and we will be merging dfs later
# Modify the existing dataframe

In [25]:
cust_raw = cust_raw.astype({
           'user_id': 'str',
           'first_name': 'str',
           'last_name': 'str',
           'gender': 'str',
           'state_name': 'str',
           'married_status': 'str'
})

In [555]:
# Special Case: pandas library is quirky about dates, so need to use a different syntax to change the datatype for a date column
# Change 'date' is not a recognized datatype in pandas, so change date_joined by using pd.to_datetime() syntax to convert the datatype
# This new datatype handles date-based calculations better and more efficiently than using an object datatype for dates

In [92]:
cust_raw['date_joined'] = pd.to_datetime(cust_raw['date_joined'])

In [159]:
# Check the profile and datatypes
cust_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 206209 entries, 0 to 206208
Data columns (total 10 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   user_id            206209 non-null  object
 1   first_name         206209 non-null  object
 2   last_name          206209 non-null  object
 3   gender             206209 non-null  object
 4   state_name         206209 non-null  object
 5   age                206209 non-null  int64
 6   date_joined        206209 non-null  datetime64[ns]
 7   number_dependents  206209 non-null  int64
 8   married_status     206209 non-null  object
 9   income             206209 non-null  int64
dtypes: datetime64[ns](1), int64(3), object(6)
memory usage: 15.7+ MB

# Step 5 - Data consistency checks

In [165]:
# Check descriptive stats for anything that looks out of place
cust_raw.describe()

,age,date_joined,number_dependents,income
count,206209.000000,206209,206209.000000,206209.000000
mean,49.501646,2018-08-17 03:06:30.029532928,1.499823,94632.852548
min,18.000000,2017-01-01 00:00:00,0.000000,25903.000000
25%,33.000000,2017-10-23 00:00:00,0.000000,59874.000000
50%,49.000000,2018-08-16 00:00:00,1.000000,93547.000000
75%,66.000000,2019-06-10 00:00:00,3.000000,124244.000000
max,81.000000,2020-04-01 00:00:00,3.000000,593901.000000
std,18.480962,NaN,1.118433,42473.786988

__Nothing looks unusual in the above descriptive stats__

# Step 5(a) - Mixed-type data

In [169]:
# Check columns of cust_raw for mixed-type data by using a custom function
# We are replacing ".applymap()" (from the Exercises) with ".map()" (which reflects updated python syntax)

for col in cust_raw.columns.tolist():
    weird = (cust_raw[[col]].map(type) != cust_raw[[col]].iloc[0].apply(type)).any(axis = 1)
    if len (cust_raw[weird]) > 0:
        print(col)

__Since there were no output column names when the for-loop script (above) ran, we do not have mixed-type data in the cust_raw dataframe__

# Step 5(b) - Missing values

In [228]:
# Identify any missing values in the dataframe using the .isnull().sum() combination of a function with an aggregation
cust_raw.isnull().sum()

user_id              0
first_name           0
last_name            0
gender               0
state_name           0
age                  0
date_joined          0
number_dependents    0
married_status       0
income               0
dtype: int64

__As per above, no columns with missing values were found by the function .isnull()__

# Step 5(c) - Duplicates

In [336]:
# Search for full duplicates (not partial duplicates) in the dataframe
# Use the .duplicated() function to find full duplicates and then store any duplicate rows in a subset "df_dups" dataframe 

df_dups = cust_raw[cust_raw.duplicated()]

__No output generated when the duplicates search code was run, so no full duplicates were found__

# Step 5(d) - Other checks

In [452]:
# Check the 'gender' column frequency distribution, to identify any inconsistent values that are not either "Female" or "Male"
cust_raw['gender'].value_counts()

gender
Male      104067
Female    102142
Name: count, dtype: int64

In [450]:
# Check the state_name column frequency distribution, to identify any inconsistent spelling of state names
# Add a .sort_index() at the end to sort the state names alphabetically, to facilitate search for inconsistent spelling

cust_raw['state_name'].value_counts().sort_index()

state_name
Alabama                 4044
Alaska                  4044
Arizona                 4044
Arkansas                4044
California              4044
Colorado                4044
Connecticut             4044
Delaware                4044
District of Columbia    4044
Florida                 4044
Georgia                 4044
Hawaii                  4044
Idaho                   4044
Illinois                4044
Indiana                 4044
Iowa                    4044
Kansas                  4043
Kentucky                4043
Louisiana               4043
Maine                   4043
Maryland                4043
Massachusetts           4043
Michigan                4043
Minnesota               4043
Mississippi             4043
Missouri                4043
Montana                 4043
Nebraska                4043
Nevada                  4043
New Hampshire           4043
New Jersey              4043
New Mexico              4043
New York                4043
North Carolina          4043
North Dakota            4043
Ohio                    4043
Oklahoma                4043
Oregon                  4043
Pennsylvania            4043
Rhode Island            4043
South Carolina          4043
South Dakota            4043
Tennessee               4043
Texas                   4043
Utah                    4043
Vermont                 4043
Virginia                4043
Washington              4043
West Virginia           4043
Wisconsin               4043
Wyoming                 4043
Name: count, dtype: int64

In [454]:
# Check 'married_status' column for value consistency

cust_raw['married_status'].value_counts()

married_status
married                             144906
single                               33962
divorced/widowed                     17640
living with parents and siblings      9701
Name: count, dtype: int64

__Based on the consistency check above, the original column name "fam_status" was slightly better than my renamed "married_status", so the column should be renamed again to a fuller, more descriptive "family_status"__

In [457]:
# Rename the 'married_status' column to be more accurately descriptive

cust_raw.rename(columns = {'married_status' : 'family_status'}, inplace = True)

In [459]:
# Check the output
cust_raw.head()

,user_id,first_name,last_name,gender,state_name,age,date_joined,number_dependents,family_status,income
0,26711,Deborah,Esquivel,Female,Missouri,48,2017-01-01,3,married,165665
1,33890,Patricia,Hart,Female,New Mexico,36,2017-01-01,0,single,59285
2,65803,Kenneth,Farley,Male,Idaho,35,2017-01-01,2,married,99568
3,125935,Michelle,Hicks,Female,Iowa,40,2017-01-01,0,single,42049
4,130797,Ann,Gilmore,Female,Maryland,26,2017-01-01,1,married,40374

In [463]:
# Check the dataframe profile
cust_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 206209 entries, 0 to 206208
Data columns (total 10 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   user_id            206209 non-null  object
 1   first_name         206209 non-null  object
 2   last_name          206209 non-null  object
 3   gender             206209 non-null  object
 4   state_name         206209 non-null  object
 5   age                206209 non-null  int64
 6   date_joined        206209 non-null  datetime64[ns]
 7   number_dependents  206209 non-null  int64
 8   family_status      206209 non-null  object
 9   income             206209 non-null  int64
dtypes: datetime64[ns](1), int64(3), object(6)
memory usage: 15.7+ MB

In [465]:
# Check the altered cust_raw dataframe dimensions
cust_raw.shape

(206209, 10)

In [469]:
# Export the cleaned dataframe to the 'Prepared Data' folder in a pickle file format, as backup

cust_raw.to_pickle(os.path.join(path, 'Data','Prepared Data', 'cust_cleaned.pkl'))

# Step 6 - Combine and export data

In [518]:
# We start by importing the ords_prods_merge file

ords_prods_merge = pd.read_pickle(os.path.join(path, 'Data', 'Prepared Data', 'ords_prods_merge_6.pkl'))

In [520]:
# Check the dimensions
ords_prods_merge.shape

(32399732, 22)

In [522]:
# Check the output
ords_prods_merge.head()

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,...,prices,price_range_loc,busiest_day,busiest_period_of_day,max_order,loyalty_flag,mean_price_per_order,spending_flag,median_days_since_prior_order,order_frequency_flag
0,2539329,1,1,2,8,NaN,196,1,0,Soda,...,9.0,Mid-range product,Regularly busy,Average orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
1,2539329,1,1,2,8,NaN,14084,2,0,Organic Unsweetened Vanilla Almond Milk,...,12.5,Mid-range product,Regularly busy,Average orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
2,2539329,1,1,2,8,NaN,12427,3,0,Original Beef Jerky,...,4.4,Low-range product,Regularly busy,Average orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
3,2539329,1,1,2,8,NaN,26088,4,0,Aged White Cheddar Popcorn,...,4.7,Low-range product,Regularly busy,Average orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
4,2539329,1,1,2,8,NaN,26405,5,0,XL Pick-A-Size Paper Towel Rolls,...,1.0,Low-range product,Regularly busy,Average orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer

In [524]:
# Check datatype of user_id (key identifier) in ords_prods_merge
ords_prods_merge['user_id'].dtype

dtype('int64')

In [ ]:
# Change datatype of 'user_id' column in ords_prods_merge to match the 'str' datatype for that column in the cust_raw dataframe

In [526]:
ords_prods_merge['user_id'] = ords_prods_merge['user_id'].astype('str')

In [532]:
# Verify change accepted
ords_prods_merge['user_id'].dtype

dtype('O')

In [534]:
# Check key identifier datatype in the other dataframe to be combined
cust_raw['user_id'].dtype

dtype('O')

__Merge the 2 dataframes using an 'inner join'__

In [536]:
# Merge cust_raw and ords_prods_merge dfs on the 'user_id' key identifier, using an 'inner join' type, include a merge flag column

ords_prods_merge_cust = ords_prods_merge.merge(cust_raw, on = ['user_id'], how = 'inner', indicator = True)

In [557]:
# Check the output
ords_prods_merge_cust.head()

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,...,first_name,last_name,gender,state_name,age,date_joined,number_dependents,family_status,income,_merge
0,2539329,1,1,2,8,NaN,196,1,0,Soda,...,Linda,Nguyen,Female,Alabama,31,2019-02-17,3,married,40423,both
1,2539329,1,1,2,8,NaN,14084,2,0,Organic Unsweetened Vanilla Almond Milk,...,Linda,Nguyen,Female,Alabama,31,2019-02-17,3,married,40423,both
2,2539329,1,1,2,8,NaN,12427,3,0,Original Beef Jerky,...,Linda,Nguyen,Female,Alabama,31,2019-02-17,3,married,40423,both
3,2539329,1,1,2,8,NaN,26088,4,0,Aged White Cheddar Popcorn,...,Linda,Nguyen,Female,Alabama,31,2019-02-17,3,married,40423,both
4,2539329,1,1,2,8,NaN,26405,5,0,XL Pick-A-Size Paper Towel Rolls,...,Linda,Nguyen,Female,Alabama,31,2019-02-17,3,married,40423,both

In [564]:
# Check the output bottom rows of combined dataframe
ords_prods_merge_cust.tail()

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,...,first_name,last_name,gender,state_name,age,date_joined,number_dependents,family_status,income,_merge
32399727,2977660,206209,13,1,12,7.0,14197,5,1,Tomato Paste,...,Diana,Donovan,Female,Iowa,74,2019-09-14,3,married,137969,both
32399728,2977660,206209,13,1,12,7.0,38730,6,0,Brownie Crunch High Protein Bar,...,Diana,Donovan,Female,Iowa,74,2019-09-14,3,married,137969,both
32399729,2977660,206209,13,1,12,7.0,31477,7,0,High Protein Bar Chunky Peanut Butter,...,Diana,Donovan,Female,Iowa,74,2019-09-14,3,married,137969,both
32399730,2977660,206209,13,1,12,7.0,6567,8,0,Chocolate Peanut Butter Protein Bar,...,Diana,Donovan,Female,Iowa,74,2019-09-14,3,married,137969,both
32399731,2977660,206209,13,1,12,7.0,22920,9,0,Roasted & Salted Shelled Pistachios,...,Diana,Donovan,Female,Iowa,74,2019-09-14,3,married,137969,both

In [559]:
# Confirm the results of the merge using the merge flag

ords_prods_merge_cust['_merge'].value_counts()

_merge
both          32399732
left_only            0
right_only           0
Name: count, dtype: int64

In [561]:
# Check the dimensions of the merged dataframe
ords_prods_merge_cust.shape

(32399732, 32)

__Drop the merge column since it's not needed after the verification__

In [566]:
# Since we will not need the '_merge' column going forward, we can drop that column

ords_prods_merge_cust = ords_prods_merge_cust.drop(columns = ['_merge'])

In [568]:
# Check the output
ords_prods_merge_cust.head()

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,...,order_frequency_flag,first_name,last_name,gender,state_name,age,date_joined,number_dependents,family_status,income
0,2539329,1,1,2,8,NaN,196,1,0,Soda,...,Non-frequent customer,Linda,Nguyen,Female,Alabama,31,2019-02-17,3,married,40423
1,2539329,1,1,2,8,NaN,14084,2,0,Organic Unsweetened Vanilla Almond Milk,...,Non-frequent customer,Linda,Nguyen,Female,Alabama,31,2019-02-17,3,married,40423
2,2539329,1,1,2,8,NaN,12427,3,0,Original Beef Jerky,...,Non-frequent customer,Linda,Nguyen,Female,Alabama,31,2019-02-17,3,married,40423
3,2539329,1,1,2,8,NaN,26088,4,0,Aged White Cheddar Popcorn,...,Non-frequent customer,Linda,Nguyen,Female,Alabama,31,2019-02-17,3,married,40423
4,2539329,1,1,2,8,NaN,26405,5,0,XL Pick-A-Size Paper Towel Rolls,...,Non-frequent customer,Linda,Nguyen,Female,Alabama,31,2019-02-17,3,married,40423

In [570]:
# Check the dimensions
ords_prods_merge_cust.shape

(32399732, 31)

# Export the combined dataframe as a pickle file format

In [575]:
# Export the newly created df as ords_prods_cust in a suitable format to the 'Prepared Data' folder

ords_prods_merge_cust.to_pickle(os.path.join(path, 'Data','Prepared Data', 'ords_prods_cust.pkl'))