# 4.8 IC Grouping data and aggregating variables

# Table of Contents

#### 01. Import libraries

#### 02. Grouping data

#### 03. Aggregating data with .agg()

#### 04. Performing multiple aggregations

#### 05. Aggregating data with .transform()

#### 06. Deriving columns with .loc()

#### 07. Export dataframe as a pickle file

# 01. Import libraries

In [4]:
# Import libraries
import pandas as pd
import numpy as np
import os

# 02. Grouping data

In [7]:
# Import ords_prods_merge_2 df from pickle file previously saved

path = r'C:\Users\dirk8\CareerFoundry Projects\03-2025 Instacart Basket Analysis'
ords_prods_merge = pd.read_pickle(os.path.join(path, 'Data', 'Prepared Data', 'ords_prods_merge_2.pkl'))

In [9]:
# Check the output
ords_prods_merge.head()

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,price_range_loc,busiest_day,busiest_days,busiest_period_of_day
0,2539329,1,1,2,8,NaN,196,1,0,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Average orders
1,2539329,1,1,2,8,NaN,14084,2,0,Organic Unsweetened Vanilla Almond Milk,91,16,12.5,Mid-range product,Regularly busy,Regularly busy,Average orders
2,2539329,1,1,2,8,NaN,12427,3,0,Original Beef Jerky,23,19,4.4,Low-range product,Regularly busy,Regularly busy,Average orders
3,2539329,1,1,2,8,NaN,26088,4,0,Aged White Cheddar Popcorn,23,19,4.7,Low-range product,Regularly busy,Regularly busy,Average orders
4,2539329,1,1,2,8,NaN,26405,5,0,XL Pick-A-Size Paper Towel Rolls,54,17,1.0,Low-range product,Regularly busy,Regularly busy,Average orders

In [11]:
# Check the dimensions
ords_prods_merge.shape

(32404859, 17)

__Create a subset df__

In [14]:
df = ords_prods_merge[:1000000]

In [16]:
# Check the dimensions
df.shape

(1000000, 17)

In [18]:
# Check the output, 10 rows this time
df.head(10)

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,price_range_loc,busiest_day,busiest_days,busiest_period_of_day
0,2539329,1,1,2,8,NaN,196,1,0,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Average orders
1,2539329,1,1,2,8,NaN,14084,2,0,Organic Unsweetened Vanilla Almond Milk,91,16,12.5,Mid-range product,Regularly busy,Regularly busy,Average orders
2,2539329,1,1,2,8,NaN,12427,3,0,Original Beef Jerky,23,19,4.4,Low-range product,Regularly busy,Regularly busy,Average orders
3,2539329,1,1,2,8,NaN,26088,4,0,Aged White Cheddar Popcorn,23,19,4.7,Low-range product,Regularly busy,Regularly busy,Average orders
4,2539329,1,1,2,8,NaN,26405,5,0,XL Pick-A-Size Paper Towel Rolls,54,17,1.0,Low-range product,Regularly busy,Regularly busy,Average orders
5,2398795,1,2,3,7,15.0,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Slowest days,Fewest orders
6,2398795,1,2,3,7,15.0,10258,2,0,Pistachios,117,19,3.0,Low-range product,Regularly busy,Slowest days,Fewest orders
7,2398795,1,2,3,7,15.0,12427,3,1,Original Beef Jerky,23,19,4.4,Low-range product,Regularly busy,Slowest days,Fewest orders
8,2398795,1,2,3,7,15.0,13176,4,0,Bag of Organic Bananas,24,4,10.3,Mid-range product,Regularly busy,Slowest days,Fewest orders
9,2398795,1,2,3,7,15.0,26088,5,1,Aged White Cheddar Popcorn,23,19,4.7,Low-range product,Regularly busy,Slowest days,Fewest orders

In [20]:
# Group the subset df as the first step of a 3-step process

df.groupby('product_name')

# 03. Aggregating data with .agg()

In [25]:
# Performing a single aggregation in 2 steps (not 3)
# The groupby() function is assigned to the df dataframe, creating a pandas Object for "department_id")
# Then the agg() function is applied onto the Object, to return the mean of the given column "order_number"

df.groupby('department_id').agg({'order_number': ['mean']})

              order_number
                      mean
department_id
1                14.800024
2                17.091743
3                17.913544
4                17.893092
5                15.214270
6                15.382135
7                17.694027
8                16.458105
9                15.957363
10               20.091818
11               16.482026
12               15.615061
13               16.484023
14               17.524632
15               15.691875
16               18.014071
17               16.150593
18               19.602850
19               17.631340
20               17.138607
21               21.956893

In [27]:
# Some aggregations can be done without the agg() function, as below
# This achieves the same results as the example above, with different syntax

df.groupby('department_id')['order_number'].mean()

department_id
1     14.800024
2     17.091743
3     17.913544
4     17.893092
5     15.214270
6     15.382135
7     17.694027
8     16.458105
9     15.957363
10    20.091818
11    16.482026
12    15.615061
13    16.484023
14    17.524632
15    15.691875
16    18.014071
17    16.150593
18    19.602850
19    17.631340
20    17.138607
21    21.956893
Name: order_number, dtype: float64

In [29]:
# In some cases, you can use dot notation, as below
# Dot notation HOWEVER is not a best practice (except for applying pandas functions, looking for dataframe attributes, etc.)
# Using it as in the example below can cause confusion to Python and/or colleagues interpreting your code -- so the brackets usage examples are better

df.groupby('department_id').order_number.mean()

department_id
1     14.800024
2     17.091743
3     17.913544
4     17.893092
5     15.214270
6     15.382135
7     17.694027
8     16.458105
9     15.957363
10    20.091818
11    16.482026
12    15.615061
13    16.484023
14    17.524632
15    15.691875
16    18.014071
17    16.150593
18    19.602850
19    17.631340
20    17.138607
21    21.956893
Name: order_number, dtype: float64

# 04. Performing multiple aggregations

In [33]:
# Expanding from producing a single statistic using agg(), to producing multiple statistics

df.groupby('department_id').agg({'order_number': ['mean', 'min', 'max']})

              order_number
                      mean min max
department_id
1                14.800024   1  99
2                17.091743   1  98
3                17.913544   1  99
4                17.893092   1  99
5                15.214270   1  99
6                15.382135   1  99
7                17.694027   1  99
8                16.458105   1  91
9                15.957363   1  99
10               20.091818   1  99
11               16.482026   1  99
12               15.615061   1  99
13               16.484023   1  99
14               17.524632   1  99
15               15.691875   1  99
16               18.014071   1  99
17               16.150593   1  99
18               19.602850   1  99
19               17.631340   1  99
20               17.138607   1  99
21               21.956893   1  97

# 05. Aggregating data with .transform()

In [40]:
# Looking to create a loyalty flag column after aggregating data with the transform() function
# Loyalty will be defined by the max order count size of a customer
# With transform, and calling the max() function from the NumPy library, the 3-step grouping and aggregation operations can be done in 1 line of code
# Note that 2 new columns will be created, initially a 'max_order' column with the help of transform, and later a loyalty flag column
# Do this for the for the full dataframe, not the subset used in examples above

ords_prods_merge['max_order'] = ords_prods_merge.groupby(['user_id'])['order_number'].transform('max')

# In response to a Python FutureWarning message on the 1-line code above, I substituted 'max' for the Exercise 4.8 use of np.max in the transform() function. After the substitution, Python did not issue a warning.

# Note to self: Exercise 4.8 wording does not explain the max order calculation well.  For clarity: it takes the highest single order size (number of products purchased) as the "max" value, for each user_id as the code is written.  The dataframe slice below, showing where the user_id transitions from 1 to 2, verifies that 10 was indeed the max for user_id = 1.

In [56]:
ords_prods_merge[53:62]

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,price_range_loc,busiest_day,busiest_days,busiest_period_of_day,max_order
53,2550362,1,10,4,8,30.0,38928,4,0,0% Greek Strained Yogurt,120,16,12.6,Mid-range product,Least busy,Slowest days,Average orders,10
54,2550362,1,10,4,8,30.0,25133,5,1,Organic String Cheese,21,16,8.6,Mid-range product,Least busy,Slowest days,Average orders,10
55,2550362,1,10,4,8,30.0,10258,6,1,Pistachios,117,19,3.0,Low-range product,Least busy,Slowest days,Average orders,10
56,2550362,1,10,4,8,30.0,35951,7,0,Organic Unsweetened Almond Milk,91,16,1.3,Low-range product,Least busy,Slowest days,Average orders,10
57,2550362,1,10,4,8,30.0,13032,8,1,Cinnamon Toast Crunch,121,14,4.0,Low-range product,Least busy,Slowest days,Average orders,10
58,2550362,1,10,4,8,30.0,12427,9,1,Original Beef Jerky,23,19,4.4,Low-range product,Least busy,Slowest days,Average orders,10
59,2168274,2,1,2,11,NaN,32792,1,0,Chipotle Beef & Pork Realstick,23,19,5.2,Mid-range product,Regularly busy,Regularly busy,Most orders,14
60,2168274,2,1,2,11,NaN,47766,2,0,Organic Avocado,24,4,6.3,Mid-range product,Regularly busy,Regularly busy,Most orders,14
61,2168274,2,1,2,11,NaN,20574,3,0,Roasted Turkey,96,20,2.3,Low-range product,Regularly busy,Regularly busy,Most orders,14

# 06. Deriving columns with .loc()

In [63]:
ords_prods_merge.loc[ords_prods_merge['max_order'] > 40, 'loyalty_flag'] = 'Loyal customer'

In [64]:
ords_prods_merge.loc[(ords_prods_merge['max_order'] <= 40) & (ords_prods_merge['max_order'] > 10), 'loyalty_flag'] = 'Regular customer'

In [65]:
ords_prods_merge.loc[ords_prods_merge['max_order'] <= 10, 'loyalty_flag'] = 'New customer'

In [89]:
# Output frequency distribution for the newly-created loyalty_flag column

ords_prods_merge['loyalty_flag'].value_counts(dropna = False)

loyalty_flag
Regular customer    15876776
Loyal customer      10284093
New customer         6243990
Name: count, dtype: int64

In [97]:
# Check a slice of columns and rows of the altered dataframe that catch the transition from one customer to the next one

ords_prods_merge[['user_id', 'loyalty_flag', 'max_order']][53:62]

    user_id      loyalty_flag  max_order
53        1      New customer         10
54        1      New customer         10
55        1      New customer         10
56        1      New customer         10
57        1      New customer         10
58        1      New customer         10
59        2  Regular customer         14
60        2  Regular customer         14
61        2  Regular customer         14

__The output above confirms that the logic of the conditional statements in the loc() functions operated as expected__

In [100]:
# Check the dimensions
ords_prods_merge.shape

(32404859, 19)

# 07. Export dataframe as a pickle file

In [103]:
# Export the dataframe as a pickle file

ords_prods_merge.to_pickle(os.path.join(path, 'Data', 'Prepared Data', 'ords_prods_merge_3.pkl'))