# 4.8 IC Task 4.8

# Table of Contents

#### 01. Import libraries

#### Step 2 - Find aggregated mean of a variable grouped by another variable

#### Step 5 - Group by a variable and check stats for another variable

#### Step 6 - Add a column followed by a flag column

#### Step 7 - Add another column followed by a flag column

#### 02. Export dataframe as a pickle file

# 01. Import libraries

In [181]:
# Import libraries

import pandas as pd
import numpy as np
import os

# Step 1

In [183]:
# Step 1: Import ords_prods_merge_5 dataframe

path = r'C:\Users\dirk8\CareerFoundry Projects\03-2025 Instacart Basket Analysis'
ords_prods_merge = pd.read_pickle(os.path.join(path, 'Data', 'Prepared Data', 'ords_prods_merge_5.pkl'))

__Comment: In a cleaning and consistency correction notebook session before this upload, I deleted a redundant (not needed) column 'busiest_days' as per Tutor feedback.  Separately, because the 'prices' column had extreme outliers skewing the descriptive stats, I deleted 4429 records that priced 'Lowfat 2% Milkfat Cottage Cheese' at 14900 and 698 records pricing '2% Reduced Fat Milk' at 99999.  A total 5127 records were deleted for data extreme inaccuracy reasons.  Before deletion I created a backup file for those records as well as the pre-alteration larger dataframe ords_prods_merge.__

In [185]:
# Check the output
ords_prods_merge.head()

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,price_range_loc,busiest_day,busiest_period_of_day,max_order,loyalty_flag
0,2539329,1,1,2,8,NaN,196,1,0,Soda,77,7,9.0,Mid-range product,Regularly busy,Average orders,10,New customer
1,2539329,1,1,2,8,NaN,14084,2,0,Organic Unsweetened Vanilla Almond Milk,91,16,12.5,Mid-range product,Regularly busy,Average orders,10,New customer
2,2539329,1,1,2,8,NaN,12427,3,0,Original Beef Jerky,23,19,4.4,Low-range product,Regularly busy,Average orders,10,New customer
3,2539329,1,1,2,8,NaN,26088,4,0,Aged White Cheddar Popcorn,23,19,4.7,Low-range product,Regularly busy,Average orders,10,New customer
4,2539329,1,1,2,8,NaN,26405,5,0,XL Pick-A-Size Paper Towel Rolls,54,17,1.0,Low-range product,Regularly busy,Average orders,10,New customer

In [186]:
# Check the dimensions
ords_prods_merge.shape

(32399732, 18)

# Step 2 - Find aggregated mean of a variable grouped by another variable

In [188]:
# Step 2: Find aggregated mean of 'order_number' column grouped by 'department_id' in the dataframe

ords_prods_merge.groupby('department_id').agg({'order_number': ['mean']})

              order_number
                      mean
department_id
1                15.457838
2                17.277920
3                17.170395
4                17.811403
5                15.215751
6                16.439806
7                17.225802
8                15.340650
9                15.895474
10               20.197148
11               16.170638
12               15.887671
13               16.583536
14               16.773669
15               16.165037
16               17.667853
17               15.694469
18               19.310397
19               17.177343
20               16.473447
21               22.902379

# Step 3 - Answer: Results for the entire ords_prods_merge df were fairly similar to those for the subset df comprised of the first 1 million records

# Step 4 - this was completed in the Exercise 4.8 notebook, resulting dataframe already imported here showing the max_order and loyalty_flag columns

# Step 5 - Group by a variable and check stats for another variable

In [192]:
# Step 5: Group customers by 'loyalty_flag' category and check basic statistics of product prices for each loyalty category

ords_prods_merge.groupby('loyalty_flag').agg({'prices': ['mean', 'min', 'max', 'std']})

                    prices
                      mean  min   max       std
loyalty_flag
Loyal customer    7.773575  1.0  25.0  4.206151
New customer      7.801206  1.0  25.0  4.266834
Regular customer  7.798262  1.0  25.0  4.254886

# Mean price of products purchased by loyal customers did not differ much from average price paid by regular or new customers. Less than 0.5%.

# Step 6 - Add a column followed by a flag column

In [195]:
# Step 6: Calculate average price per customer across all their orders
# Then create a spending flag for each customer that labels price < 10 as "Low spender" and >= 10 as "High spender"

In [196]:
ords_prods_merge['mean_order'] = ords_prods_merge.groupby(['user_id'])['prices'].transform('mean')

In [197]:
# Check the output
ords_prods_merge[56:61]

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,price_range_loc,busiest_day,busiest_period_of_day,max_order,loyalty_flag,mean_order
56,2550362,1,10,4,8,30.0,35951,7,0,Organic Unsweetened Almond Milk,91,16,1.3,Low-range product,Least busy,Average orders,10,New customer,6.367797
57,2550362,1,10,4,8,30.0,13032,8,1,Cinnamon Toast Crunch,121,14,4.0,Low-range product,Least busy,Average orders,10,New customer,6.367797
58,2550362,1,10,4,8,30.0,12427,9,1,Original Beef Jerky,23,19,4.4,Low-range product,Least busy,Average orders,10,New customer,6.367797
59,2168274,2,1,2,11,NaN,32792,1,0,Chipotle Beef & Pork Realstick,23,19,5.2,Mid-range product,Regularly busy,Most orders,14,Regular customer,7.515897
60,2168274,2,1,2,11,NaN,47766,2,0,Organic Avocado,24,4,6.3,Mid-range product,Regularly busy,Most orders,14,Regular customer,7.515897

In [198]:
# Check the dimensions
ords_prods_merge.shape

(32399732, 19)

In [199]:
# Create the spending flag

In [232]:
ords_prods_merge.loc[ords_prods_merge['mean_order'] >= 10, 'spending_flag'] = 'High spender'

In [233]:
ords_prods_merge.loc[ords_prods_merge['mean_order'] < 10, 'spending_flag'] = 'Low spender'

In [249]:
# Check the output
ords_prods_merge[56:61]

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,price_range_loc,busiest_day,busiest_period_of_day,max_order,loyalty_flag,mean_order,spending_flag
56,2550362,1,10,4,8,30.0,35951,7,0,Organic Unsweetened Almond Milk,91,16,1.3,Low-range product,Least busy,Average orders,10,New customer,6.367797,Low spender
57,2550362,1,10,4,8,30.0,13032,8,1,Cinnamon Toast Crunch,121,14,4.0,Low-range product,Least busy,Average orders,10,New customer,6.367797,Low spender
58,2550362,1,10,4,8,30.0,12427,9,1,Original Beef Jerky,23,19,4.4,Low-range product,Least busy,Average orders,10,New customer,6.367797,Low spender
59,2168274,2,1,2,11,NaN,32792,1,0,Chipotle Beef & Pork Realstick,23,19,5.2,Mid-range product,Regularly busy,Most orders,14,Regular customer,7.515897,Low spender
60,2168274,2,1,2,11,NaN,47766,2,0,Organic Avocado,24,4,6.3,Mid-range product,Regularly busy,Most orders,14,Regular customer,7.515897,Low spender

In [251]:
# Rename 'mean_order' column (not descriptive enough) to 'mean_price_per_order'

ords_prods_merge.rename(columns = {'mean_order':'mean_price_per_order'}, inplace=True)

In [264]:
# Check the output
ords_prods_merge[56:61]

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,price_range_loc,busiest_day,busiest_period_of_day,max_order,loyalty_flag,mean_price_per_order,spending_flag
56,2550362,1,10,4,8,30.0,35951,7,0,Organic Unsweetened Almond Milk,91,16,1.3,Low-range product,Least busy,Average orders,10,New customer,6.367797,Low spender
57,2550362,1,10,4,8,30.0,13032,8,1,Cinnamon Toast Crunch,121,14,4.0,Low-range product,Least busy,Average orders,10,New customer,6.367797,Low spender
58,2550362,1,10,4,8,30.0,12427,9,1,Original Beef Jerky,23,19,4.4,Low-range product,Least busy,Average orders,10,New customer,6.367797,Low spender
59,2168274,2,1,2,11,NaN,32792,1,0,Chipotle Beef & Pork Realstick,23,19,5.2,Mid-range product,Regularly busy,Most orders,14,Regular customer,7.515897,Low spender
60,2168274,2,1,2,11,NaN,47766,2,0,Organic Avocado,24,4,6.3,Mid-range product,Regularly busy,Most orders,14,Regular customer,7.515897,Low spender

In [266]:
# Check the dimensions
ords_prods_merge.shape

(32399732, 20)

In [268]:
# Check the distribution
ords_prods_merge['spending_flag'].value_counts()

spending_flag
Low spender     32280013
High spender      119719
Name: count, dtype: int64

__Not a lot of high spenders.  This might also result from an average 'prices' = 10 threshold between low and high spenders possibly acting as a high hurdle number relative to the earlier removal of 5127 records distorted by 'prices' outliers that were causing a heavy upward skew to average prices and standard deviation of these.  In other words, correcting prices upward skew due to inaccurate prices data (by removing the associated 5127 records) reduced the average prices level materially.__

# Step 7 - Add another column followed by a flag column

In [ ]:
# Step 7: Determine median per customer for 'days_since_prior_order' column, to help determine frequent vs non-frequent customers
# Create an order frequency flag based off the median, to label each customer's ordering behavior

# NOTE to self: I created a 1000-row ords_prods_merge dataframe subset as a "sandbox" to test the median-calculating line of code before applying it to the full dataframe. A WarningMessage alerted me to the fact that I had created a "view" (which apparently stays connected to, and if operated on, might alter the "parent" dataframe it was created from).  If then altering a view (rather than just displaying it), python gets confused, does not like that. ChatGPT offered a clean solution: when planning to alter the view (i.e. adding a column, etc.), always, always, always make a COPY of the view, then operate on the COPY.  The copy "severs" the link with the "parent" dataframe.  Correct syntax to create the copy was: df_sub = ords_prods_merge[:1000].copy(). Will adopt this copy-based approach (if planning to alter a subset view for sandbox purposes, rather than simply display the view) going forward.

In [300]:
ords_prods_merge['median_days_since_prior_order'] = ords_prods_merge.groupby(['user_id'])['days_since_prior_order'].transform('median')

In [308]:
# Check the output to compare 2 customers in the row area that transitions to the 2nd customer
# This approach saves RAM usage, memory in the current session. It's not necessary to look at 100+ rows for verification purposes.
ords_prods_merge[56:61]

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,...,department_id,prices,price_range_loc,busiest_day,busiest_period_of_day,max_order,loyalty_flag,mean_price_per_order,spending_flag,median_days_since_prior_order
56,2550362,1,10,4,8,30.0,35951,7,0,Organic Unsweetened Almond Milk,...,16,1.3,Low-range product,Least busy,Average orders,10,New customer,6.367797,Low spender,20.5
57,2550362,1,10,4,8,30.0,13032,8,1,Cinnamon Toast Crunch,...,14,4.0,Low-range product,Least busy,Average orders,10,New customer,6.367797,Low spender,20.5
58,2550362,1,10,4,8,30.0,12427,9,1,Original Beef Jerky,...,19,4.4,Low-range product,Least busy,Average orders,10,New customer,6.367797,Low spender,20.5
59,2168274,2,1,2,11,NaN,32792,1,0,Chipotle Beef & Pork Realstick,...,19,5.2,Mid-range product,Regularly busy,Most orders,14,Regular customer,7.515897,Low spender,13.0
60,2168274,2,1,2,11,NaN,47766,2,0,Organic Avocado,...,4,6.3,Mid-range product,Regularly busy,Most orders,14,Regular customer,7.515897,Low spender,13.0

In [310]:
# Check the dimensions
ords_prods_merge.shape

(32399732, 21)

In [314]:
# Create the order frequency flag

In [315]:
ords_prods_merge.loc[ords_prods_merge['median_days_since_prior_order'] > 20, 'order_frequency_flag'] = 'Non-frequent customer'

In [316]:
ords_prods_merge.loc[(ords_prods_merge['median_days_since_prior_order'] > 10) & (ords_prods_merge['median_days_since_prior_order'] <= 20), 'order_frequency_flag'] = 'Regular customer'

In [317]:
ords_prods_merge.loc[ords_prods_merge['median_days_since_prior_order'] <= 10, 'order_frequency_flag'] = 'Frequent customer'

In [333]:
# Check the output
ords_prods_merge[56:61]

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,...,prices,price_range_loc,busiest_day,busiest_period_of_day,max_order,loyalty_flag,mean_price_per_order,spending_flag,median_days_since_prior_order,order_frequency_flag
56,2550362,1,10,4,8,30.0,35951,7,0,Organic Unsweetened Almond Milk,...,1.3,Low-range product,Least busy,Average orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
57,2550362,1,10,4,8,30.0,13032,8,1,Cinnamon Toast Crunch,...,4.0,Low-range product,Least busy,Average orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
58,2550362,1,10,4,8,30.0,12427,9,1,Original Beef Jerky,...,4.4,Low-range product,Least busy,Average orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
59,2168274,2,1,2,11,NaN,32792,1,0,Chipotle Beef & Pork Realstick,...,5.2,Mid-range product,Regularly busy,Most orders,14,Regular customer,7.515897,Low spender,13.0,Regular customer
60,2168274,2,1,2,11,NaN,47766,2,0,Organic Avocado,...,6.3,Mid-range product,Regularly busy,Most orders,14,Regular customer,7.515897,Low spender,13.0,Regular customer

In [335]:
# Check the dimensions
ords_prods_merge.shape

(32399732, 22)

In [341]:
# Check the distribution
ords_prods_merge['order_frequency_flag'].value_counts()

order_frequency_flag
Frequent customer        21556644
Regular customer          7207340
Non-frequent customer     3635743
Name: count, dtype: int64

# 02. Export dataframe as a pickle file

In [343]:
# Export the dataframe as a pickle file

ords_prods_merge.to_pickle(os.path.join(path, 'Data', 'Prepared Data', 'ords_prods_merge_6.pkl'))