# 4.6 IC TASK 4.6

# Table of Contents

#### 01. Import libraries

#### 02. Combining data

#### Step 3 - Import pickle file

#### Step 4 - Assess the imported dataframe

#### Step 5 - Merge dataframes

#### Step 6 - Confirm results

#### Step 7 - Drop _merge flag column and export as pickle file

# 01. Import libraries

In [6]:
# Import libraries
import pandas as pd
import numpy as np
import os

# 02. Combining data

# Step 3 - Import pickle file

In [10]:
# Step 3: Import order_products_combined df from pickly file previously saved

path = r'C:\Users\dirk8\CareerFoundry Projects\03-2025 Instacart Basket Analysis'
df_orders_products_combined = pd.read_pickle(os.path.join(path, 'Data', 'Prepared Data', 'orders_products_combined.pkl'))

# Step 4 - Assess the imported dataframe

In [13]:
# Step 4: Check the shape of the imported df
df_orders_products_combined.shape

(32434489, 10)

In [15]:
# Comment: The imported df matches the dimensions of the exported df (in a separate Notebook) exactly

In [23]:
# Check the output
df_orders_products_combined.head()

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,_merge
0,2539329,1,1,2,8,NaN,196,1,0,both
1,2539329,1,1,2,8,NaN,14084,2,0,both
2,2539329,1,1,2,8,NaN,12427,3,0,both
3,2539329,1,1,2,8,NaN,26088,4,0,both
4,2539329,1,1,2,8,NaN,26405,5,0,both

In [90]:
# Note: The last column, '_merge', is not needed for next steps so we drop it
# This was run: df_orders_products_combined = df_orders_products_combined.drop(columns = ['_merge'])

In [32]:
# Check the output
df_orders_products_combined.head()

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered
0,2539329,1,1,2,8,NaN,196,1,0
1,2539329,1,1,2,8,NaN,14084,2,0
2,2539329,1,1,2,8,NaN,12427,3,0
3,2539329,1,1,2,8,NaN,26088,4,0
4,2539329,1,1,2,8,NaN,26405,5,0

In [36]:
# Check the dimensions
df_orders_products_combined.shape

(32434489, 9)

In [17]:
# Import the wrangled, cleaned and deduped products dataset stored in "Prepared Data" folder from previous Exercise 4.5

df_prods = pd.read_csv(os.path.join(path, 'Data', 'Prepared Data', 'products_checked.csv'), index_col = False)

In [19]:
# Check the output
df_prods.head()

,product_id,product_name,aisle_id,department_id,prices
0,1,Chocolate Sandwich Cookies,61,19,5.8
1,2,All-Seasons Salt,104,13,9.3
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.5
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.5
4,5,Green Chile Anytime Sauce,5,13,4.3

In [21]:
# Check dimensions
df_prods.shape

(49672, 5)

# Step 5 - Merge dataframes

In [77]:
# Step 5: Determine a suitable way to combine df_orders_products_combined and df_prods
# To get a full picture and help me decide, I first ran an "outer" join, omitted here for laptop RAM conservation purposes
# Resulting merge flag frequencies were: "both" 32,404,859 records, "left_only" 30,200 records, "right_only" 11 records
# The dimensions were 32,435,070 x 14
# The implied proportionally tiny 0.09% of records (30,211 / 32,435,070) lying outside the overlap zone of the 2 dfs caused me to choose "inner" join
# This will merge only those records from the 2 dfs that can find a matching 'product_id'

In [69]:
df_ords_prods_merge = df_orders_products_combined.merge(df_prods, on = ['product_id'], how = 'inner', indicator = True)

In [71]:
# Check the output
df_ords_prods_merge.head()

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,_merge
0,2539329,1,1,2,8,NaN,196,1,0,Soda,77,7,9.0,both
1,2539329,1,1,2,8,NaN,14084,2,0,Organic Unsweetened Vanilla Almond Milk,91,16,12.5,both
2,2539329,1,1,2,8,NaN,12427,3,0,Original Beef Jerky,23,19,4.4,both
3,2539329,1,1,2,8,NaN,26088,4,0,Aged White Cheddar Popcorn,23,19,4.7,both
4,2539329,1,1,2,8,NaN,26405,5,0,XL Pick-A-Size Paper Towel Rolls,54,17,1.0,both

# Step 6 - Confirm results

In [73]:
# Step 6: Confirm the results of the merge using the merge flag

df_ords_prods_merge['_merge'].value_counts()

_merge
both          32404859
left_only            0
right_only           0
Name: count, dtype: int64

In [83]:
# Confirm dimensions
df_ords_prods_merge.shape

(32404859, 14)

# Step 7 - Drop _merge flag column and export as pickle file

In [92]:
# Step 7: Export the newly created df as ords_prods_merge in a suitable format
# First we will drop the '_merge' flag column as it served its purpose, is not needed for next steps and all its values are the same

df_ords_prods_merge = df_ords_prods_merge.drop(columns = ['_merge'])

In [94]:
# Check the output
df_ords_prods_merge.head()

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices
0,2539329,1,1,2,8,NaN,196,1,0,Soda,77,7,9.0
1,2539329,1,1,2,8,NaN,14084,2,0,Organic Unsweetened Vanilla Almond Milk,91,16,12.5
2,2539329,1,1,2,8,NaN,12427,3,0,Original Beef Jerky,23,19,4.4
3,2539329,1,1,2,8,NaN,26088,4,0,Aged White Cheddar Popcorn,23,19,4.7
4,2539329,1,1,2,8,NaN,26405,5,0,XL Pick-A-Size Paper Towel Rolls,54,17,1.0

In [96]:
# Check dimensions
df_ords_prods_merge.shape

(32404859, 13)

In [98]:
# Export using a pickle file format for better compression (of a large file) rationale

df_ords_prods_merge.to_pickle(os.path.join(path, 'Data', 'Prepared Data', 'ords_prods_merge.pkl'))