# 4.6 IC Exercise - Demo Practice

# Table of Contents

#### 01. Import libraries

#### 02. Create dictionaries - convert into dataframes

#### 03. Concatenate dataframes

#### 04. Merge dataframes

# 01. Import libraries

In [3]:
# Import libraries
import pandas as pd
import numpy as np
import os

# 02. Create dictionaries - convert into dataframes

In [5]:
# Define a dictionary containing January 2020 data
data1 = {'customer_id':['6732', '767', '890', '635'],
         'month':['Jan-20', 'Jan-20', 'Jan-20', 'Jan-20'],
         'purchased_meat':[0, 13, 3, 4],
         'purchased_alcohol':[1, 2, 10, 0],
         'purchased_snacks':[10, 5, 1, 7]}

In [7]:
# Define a dictionary containing February 2020 data
data2 = {'customer_id':['6732', '767', '890', '635'],
         'month':['Feb-20', 'Feb-20', 'Feb-20', 'Feb-20'],
         'purchased_meat':[0, 10, 5, 3],
         'purchased_alcohol':[2, 4, 14, 0],
         'purchased_snacks':[15, 3, 2, 6]}

In [11]:
# Convert the dictionary into dataframe
df = pd.DataFrame(data1,index = [0, 1, 2, 3])
df_1 = pd.DataFrame(data2,index = [0, 1, 2, 3])

In [13]:
df

  customer_id   month  purchased_meat  purchased_alcohol  purchased_snacks
0        6732  Jan-20               0                  1                10
1         767  Jan-20              13                  2                 5
2         890  Jan-20               3                 10                 1
3         635  Jan-20               4                  0                 7

In [15]:
df_1

  customer_id   month  purchased_meat  purchased_alcohol  purchased_snacks
0        6732  Feb-20               0                  2                15
1         767  Feb-20              10                  4                 3
2         890  Feb-20               5                 14                 2
3         635  Feb-20               3                  0                 6

In [17]:
# Create a list that contains our dataframes

frames = [df, df_1]

In [19]:
# Check the output
frames

[  customer_id   month  purchased_meat  purchased_alcohol  purchased_snacks
 0        6732  Jan-20               0                  1                10
 1         767  Jan-20              13                  2                 5
 2         890  Jan-20               3                 10                 1
 3         635  Jan-20               4                  0                 7,
   customer_id   month  purchased_meat  purchased_alcohol  purchased_snacks
 0        6732  Feb-20               0                  2                15
 1         767  Feb-20              10                  4                 3
 2         890  Feb-20               5                 14                 2
 3         635  Feb-20               3                  0                 6]

In [21]:
# Check the datatypes to be sure it is a list
type(frames)

list

# 03. Concatenate dataframes

In [23]:
# Concatenate the dataframes using default options

df_concat = pd.concat(frames)

In [25]:
# Check the output
df_concat

  customer_id   month  purchased_meat  purchased_alcohol  purchased_snacks
0        6732  Jan-20               0                  1                10
1         767  Jan-20              13                  2                 5
2         890  Jan-20               3                 10                 1
3         635  Jan-20               4                  0                 7
0        6732  Feb-20               0                  2                15
1         767  Feb-20              10                  4                 3
2         890  Feb-20               5                 14                 2
3         635  Feb-20               3                  0                 6

In [27]:
# Concatenate the dataframes using the axis = 1 --> create a wide format as an output

df_concat = pd.concat(frames, axis = 1)

In [29]:
# Check the output
df_concat

,customer_id,month,purchased_meat,purchased_alcohol,purchased_snacks,customer_id,month,purchased_meat,purchased_alcohol,purchased_snacks
0,6732,Jan-20,0,1,10,6732,Feb-20,0,2,15
1,767,Jan-20,13,2,5,767,Feb-20,10,4,3
2,890,Jan-20,3,10,1,890,Feb-20,5,14,2
3,635,Jan-20,4,0,7,635,Feb-20,3,0,6

# 04. Merge dataframes

In [34]:
# Create data with different columns from df

data3 = {'customer_id':['6732', '767', '890', '635'],
         'month':['Jan-20', 'Jan-20', 'Jan-20', 'Jan-20'],
         'days_purchased_on':[0, 10, 4, 1]}

In [38]:
# Convert to dataframe

df_2 = pd.DataFrame(data3,index=[0, 1, 2, 3])

In [40]:
df_2

  customer_id   month  days_purchased_on
0        6732  Jan-20                  0
1         767  Jan-20                 10
2         890  Jan-20                  4
3         635  Jan-20                  1

In [42]:
# Merge df and df_2 using customer_id as a key 

df_merged = df.merge(df_2, on = 'customer_id')

In [44]:
df_merged

,customer_id,month_x,purchased_meat,purchased_alcohol,purchased_snacks,month_y,days_purchased_on
0,6732,Jan-20,0,1,10,Jan-20,0
1,767,Jan-20,13,2,5,Jan-20,10
2,890,Jan-20,3,10,1,Jan-20,4
3,635,Jan-20,4,0,7,Jan-20,1

In [48]:
# Merge df and df_2 using customer_id and month as a keys 

df_merged = df.merge(df_2, on = ['customer_id', 'month'])

In [50]:
df_merged

,customer_id,month,purchased_meat,purchased_alcohol,purchased_snacks,days_purchased_on
0,6732,Jan-20,0,1,10,0
1,767,Jan-20,13,2,5,10
2,890,Jan-20,3,10,1,4
3,635,Jan-20,4,0,7,1

In [52]:
# Merge df and df_2 using customer_id and month as a keys, add a merge flag

df_merged = df.merge(df_2, on = ['customer_id', 'month'], indicator = True)

In [54]:
df_merged

,customer_id,month,purchased_meat,purchased_alcohol,purchased_snacks,days_purchased_on,_merge
0,6732,Jan-20,0,1,10,0,both
1,767,Jan-20,13,2,5,10,both
2,890,Jan-20,3,10,1,4,both
3,635,Jan-20,4,0,7,1,both

In [56]:
df_merged['_merge'].value_counts()

_merge
both          4
left_only     0
right_only    0
Name: count, dtype: int64

In [58]:
# Test merge without overwriting

pd.merge(df, df_2, on = ['customer_id', 'month'], indicator = True)

,customer_id,month,purchased_meat,purchased_alcohol,purchased_snacks,days_purchased_on,_merge
0,6732,Jan-20,0,1,10,0,both
1,767,Jan-20,13,2,5,10,both
2,890,Jan-20,3,10,1,4,both
3,635,Jan-20,4,0,7,1,both